"""empty message

Revision ID: 318dae349b2e
Revises: 9afc41f15ddc
Create Date: 2024-01-12 15:05:05.314017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318dae349b2e'
down_revision = '9afc41f15ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('svar',
    sa.Column('svar_id', sa.Integer(), nullable=False),
    sa.Column('overskrift', sa.String(), nullable=False),
    sa.Column('svar_innhold', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('svar_id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.drop_table('svar')
    # ### end Alembic commands ###
